export const PLUGINS_LIST = [
  'plugin-syntax-typescript',
  'typescript',
  'asyncGenerators',
  'bigInt',
  'classProperties',
  'classPrivateProperties',
  'classPrivateMethods',
  'doExpressions',
  'dynamicImport',
  'exportDefaultFrom',
  'exportNamespaceFrom',
  'functionBind',
  'functionSent',
  'importMeta',
  'logicalAssignment',
  'nullishCoalescingOperator',
  'numericSeparator',
  'objectRestSpread',
  'optionalCatchBinding',
  'optionalChaining',
  'partialApplication',
  ['pipelineOperator', { proposal: 'smart' }],
  'throwExpressions',
  'topLevelAwait',
  'decorators-legacy',
  ['@babel/plugin-syntax-decorators', 'decorators', { decoratorsBeforeExport: true }]
]
